const synopsis = {
  true: {
    true: "You feel your life has a valued meaning and purpose, yet you are still openly exploring that meaning or purpose. Life's meaning is an ever-unfolding and ever-deepening process for you. You are more drawn to the question, \"what can my life mean?\" than to any single answer. You are likely satisfied with your life, generally optimistic, experience feelings of love frequently, and rarely feel depressed or anxious. You may be somewhat active in religious activities, but regardless of your involvement in religion, you are likely to feel that your spirituality is important to you. You place less value on pursuing simple sensory stimulation and pleasure than other people. You are generally certain of, and occasionally forceful regarding, your views and beliefs. Although you could be said to prefer having a stable structure in society and life, you see many areas for improvement to the current situation. People who know you would probably describe you as conscientious, thoughtful, easy to get along with, open to new experiences, and generally easy-going and emotionally stable.",
    false: "You feel your life has a valued meaning and purpose, and are not actively exploring that meaning or seeking meaning in your life. One might say that you are satisfied that you've grasped what makes your life meaningful, why you're here, and what you want to do with your life. You are probably highly satisfied with your life, optimistic, and have a healthy self-esteem. You frequently experience feelings of love and joy, and rarely feel afraid, angry, ashamed, or sad. You probably hold traditional values. You are usually certain of, and often forceful regarding, your views and likely support structure and rules for society and living. You are probably active in and committed to religious pursuits. People who know you would probably describe you as conscientious, organized, friendly, easy to get along with, and socially outgoing."
  },
  false: {
    true: "You probably do not feel your life has a valued meaning and purpose, and you are actively searching for something or someone that will give your life meaning or purpose. You may feel lost in life, and this idea may cause you distress. You are probably not always satisfied with your life. You may not experience emotions like love and joy that often. You may occasionally, or even often, feel anxious, nervous, or sad and depressed. You are probably questioning the role of religion in your life, and may be working hard to figure out whether there is a God, what life on Earth is really about, and which, if any, religion is right for you. People who know you would probably describe you as liking to play things by ear, or \"go with the flow\" when it comes to plans. They might find you to be worried on occasion, and not particularly socially active.",
    false: "You probably do not feel your life has a valued meaning and purpose, and are not actively exploring that meaning or seeking meaning in your life. Overall, you probably don't find the idea of thinking about your life's meaning very interesting or important. You may not always be satisfied with your life, or yourself, and you might not be particularly optimistic about the future. You may not experience emotions like love and joy that often. You may occasionally, or even often, feel anxious, nervous, or sad and depressed. You are probably do not hold traditional values, and may be more likely to value stimulating, exciting experiences, although you are not necessarily open-minded about everything. When you have big decisions to make, you may be prefer to identify the right answer based on your confidence that \"you'll know it when you see it.\" People who know you would probably describe you as sometimes disorganized, occasionally nervous or tense, and not particularly socially active or especially warm towards everyone."
  }
}

export default synopsis;
